@startuml "Barrilete Cosmico"

object barrileteCosmico{
    destinos = [lastToninas, garlicsSea, goodAirs, silversSea]
    usuarios = {pabloHari}
    mediosDeTransporte = [avion,tren]

    obtenerDestinoMasImportantes()
    aplicarDescuentosALosDestinos()
    esEmpresaExtrema()
    cartaDeDestinos()
    armarViaje(unUsuario, unDestino)
}

class Localidad {
    nombre
    equipajeImprecindible
    kilometroDeUbicacion
    precio
    esDestacado()
    aplicarDescuento(unDescuento)
    reducirPrecio(unDescuento)
    agregarEquipaje(equipaje)
    esDestinoPeligroso()
    calcularDistancia(otraLocalidad)
}

class Usuario{
    nombre
    localidadDeOrigen
    dinero
    viajes
    usuariosQueSigue
    viajarA(destino)
    puedeViajar(destino)
    comprarPasaje(destino)
    agregarDestino(destino)
    kilometros()
    seguirUsuario(unUsuario)
    devolverFollow(unUsuario)
    hacerViaje(unViaje)

}
class Viaje{
    origen
    destino
    medioDeTransporte
    distanciaRecorrida()
    precioDeViaje()
}
class Transporte{
    tiempoDeViaje
    precioPorKilometro
    precioDeTransporte(unosKilometros)
}
object avion{
    tiempoDeViaje = 60
    precioPorKilometro = 100
}
object tren{
    tiempoDeViaje = 120
    precioPorKilometro = 50
}
object lastToninas{
    nombre = "Last Toninas"
    equipajeImprecindible =  ["vacuna gripal", "vacuna B", "necronomicon"]
    precio = 3500
    kilometroDeUbicacion = 50

}

object silverSea{
    nombre = "Silver's Sea"
	equipajeImprecindible = ["protector solar", "equipo de buceo"]
	precio = 1350
    kilometroDeUbicacion = 350
}

object goodAirs{
    nombre = "Good Airs"
	equipajeImprecindible = ["cerveza", "protector solar"]
	precio = 1500
    kilometroDeUbicacion = 200
}

object garlicSea {
    nombre = "Garlic's Sea"
	equipajeImprecindible = ["caña de pescar", "piloto"] 
	precio = 2500
    kilometroDeUbicacion = 100
}

object pHari{
    nombreUsuario = "Pablo Hari"
	destinosVisitados = [lastToninas, goodAirs]
	dinero = 1500
	seguidos = []
}

lastToninas --|> Localidad
goodAirs    --|> Localidad
silverSea   --|> Localidad
garlicSea   --|> Localidad
pHari   --|> Usuario
tren --|> Transporte
avion --|> Transporte

Viaje ..> Transporte 
Viaje ..> Localidad 
barrileteCosmico -->"*" Localidad
barrileteCosmico-->"*" Usuario
barrileteCosmico-->"*" Transporte
barrileteCosmico--> Viaje

@enduml
